### ISSUE TITLE
ErrorException in navigation.twig line 21

### ISSUE THREAD

**Issue by edmeehan** [anomalylabs/starter-theme#1]
Error:
An exception has been thrown during the rendering of a template ("The function "page" does not exist. Did you mean "page_nav" in "/var/www/pohoiki/core/anomaly/pages-module/resources/views/nav.twig" at line 4") in "theme::partials/navigation" at line 21.

Temp solution:
remove line 21 of starter-theme/resources/views/partials/navigation.twig solve issue

Environment:
ubuntu-15.10 LAMP stack

**Comment by RyanThompson** [comment]
Ah shoot..
